application: madlab-ndm
version: 1
runtime: python
api_version: 1

handlers:
- url: /thing/.*
  script: thing.py
  login: required
  
- url: /annotation/.*
  script: annotation.py
  login: required

- url: /generate
  script: generate.py
  login: required

- url: /css
  static_dir: css

- url: .*
  script: main.py

builtins:
  - remote_api: on